<a href="https://colab.research.google.com/github/anp2/Declarative-Pipeline/blob/master/EcommProj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files

uploaded = files.upload()

Saving CustomersData.csv to CustomersData.csv
Saving Tax_amount.xlsx to Tax_amount.xlsx
Saving Online_Sales.csv to Online_Sales.csv
Saving Marketing_Spend.csv to Marketing_Spend.csv
Saving Discount_Coupon.csv to Discount_Coupon.csv

In [3]:
customer_df = pd.read_csv('CustomersData.csv')

disc_coupon_df = pd.read_csv('Discount_Coupon.csv')

sales_df = pd.read_csv('Online_Sales.csv')

marketing_df = pd.read_csv('Marketing_Spend.csv')

tax_df = pd.read_excel('Tax_amount.xlsx')

In [4]:
print("Customer Data")
display(customer_df.head())

print("Discount Coupon")
display(disc_coupon_df.head())

print("Online Sales")
display(sales_df.head())

print("Marketing Spend")
display(marketing_df.head())

print("Tax Data")
display(tax_df.head())

Customer Data

   CustomerID Gender    Location  Tenure_Months
0       17850      M     Chicago             12
1       13047      M  California             43
2       12583      M     Chicago             33
3       13748      F  California             30
4       15100      M  California             49

Discount Coupon

  Month Product_Category Coupon_Code  Discount_pct
0   Jan          Apparel      SALE10            10
1   Feb          Apparel      SALE20            20
2   Mar          Apparel      SALE30            30
3   Jan         Nest-USA      ELEC10            10
4   Feb         Nest-USA      ELEC20            20

Online Sales

,CustomerID,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status
0,17850,16679,1/1/2019,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used
1,17850,16680,1/1/2019,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used
2,17850,16681,1/1/2019,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,1,2.05,6.5,Used
3,17850,16682,1/1/2019,GGOEGAAB010516,Google Men's 100% Cotton Short Sleeve Hero Tee...,Apparel,5,17.53,6.5,Not Used
4,17850,16682,1/1/2019,GGOEGBJL013999,Google Canvas Tote Natural/Navy,Bags,1,16.50,6.5,Used

Marketing Spend

       Date  Offline_Spend  Online_Spend
0  1/1/2019           4500       2424.50
1  1/2/2019           4500       3480.36
2  1/3/2019           4500       1576.38
3  1/4/2019           4500       2928.55
4  1/5/2019           4500       4055.30

Tax Data

  Product_Category   GST
0         Nest-USA  0.10
1           Office  0.10
2          Apparel  0.18
3             Bags  0.18
4        Drinkware  0.18

In [5]:
print("Customer Data:", customer_df.shape)

print("Doscount Coupon:", disc_coupon_df.shape)

print("Online Sales:", sales_df.shape)

print("Marketing Spend:", marketing_df.shape)

print("Tax Data:", tax_df.shape)

Customer Data: (1468, 4)
Doscount Coupon: (204, 4)
Online Sales: (52924, 10)
Marketing Spend: (365, 3)
Tax Data: (20, 2)

In [6]:
customer_df.info()

disc_coupon_df.info()

sales_df.info()

marketing_df.info()

tax_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1468 entries, 0 to 1467
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     1468 non-null   int64
 1   Gender         1468 non-null   object
 2   Location       1468 non-null   object
 3   Tenure_Months  1468 non-null   int64
dtypes: int64(2), object(2)
memory usage: 46.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Month             204 non-null    object
 1   Product_Category  204 non-null    object
 2   Coupon_Code       204 non-null    object
 3   Discount_pct      204 non-null    int64
dtypes: int64(1), object(3)
memory usage: 6.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52924 entries, 0 to 52923
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CustomerID           52924 non-null  int64
 1   Transaction_ID       52924 non-null  int64
 2   Transaction_Date     52924 non-null  object
 3   Product_SKU          52924 non-null  object
 4   Product_Description  52924 non-null  object
 5   Product_Category     52924 non-null  object
 6   Quantity             52924 non-null  int64
 7   Avg_Price            52924 non-null  float64
 8   Delivery_Charges     52924 non-null  float64
 9   Coupon_Status        52924 non-null  object
dtypes: float64(2), int64(3), object(5)
memory usage: 4.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           365 non-null    object
 1   Offline_Spend  365 non-null    int64
 2   Online_Spend   365 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 8.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product_Category  20 non-null     object
 1   GST               20 non-null     float64
dtypes: float64(1), object(1)
memory usage: 452.0+ bytes

In [7]:
print(customer_df.dtypes)

CustomerID        int64
Gender           object
Location         object
Tenure_Months     int64
dtype: object

In [8]:
print(disc_coupon_df.dtypes)

Month               object
Product_Category    object
Coupon_Code         object
Discount_pct         int64
dtype: object

In [9]:
print(sales_df.dtypes)

CustomerID               int64
Transaction_ID           int64
Transaction_Date        object
Product_SKU             object
Product_Description     object
Product_Category        object
Quantity                 int64
Avg_Price              float64
Delivery_Charges       float64
Coupon_Status           object
dtype: object

In [10]:
print(marketing_df.dtypes)

Date              object
Offline_Spend      int64
Online_Spend     float64
dtype: object

In [11]:
print(tax_df.dtypes)

Product_Category     object
GST                 float64
dtype: object

In [12]:
sales_df['CustomerID'] = sales_df['CustomerID'].astype(str)

In [13]:
sales_df['Transaction_ID'] = sales_df['Transaction_ID'].astype(str)

In [14]:
sales_df['Product_SKU'] = sales_df['Product_SKU'].astype(str)

In [15]:
customer_df['CustomerID'] = customer_df['CustomerID'].astype(str)

In [16]:
print(sales_df.dtypes)

CustomerID              object
Transaction_ID          object
Transaction_Date        object
Product_SKU             object
Product_Description     object
Product_Category        object
Quantity                 int64
Avg_Price              float64
Delivery_Charges       float64
Coupon_Status           object
dtype: object

In [17]:
sales_df['Transaction_Date'] = pd.to_datetime(
    sales_df['Transaction_Date']
)

marketing_df['Date'] = pd.to_datetime(
    marketing_df['Date']
)

In [18]:
print(marketing_df.dtypes)

Date             datetime64[ns]
Offline_Spend             int64
Online_Spend            float64
dtype: object

In [19]:
for name, df in customer_df.items():

    print('=' * 60)

    print(name)

    print('=' * 60)

    print(df.isnull().sum())

    print('\n')

============================================================
CustomerID
============================================================
0


============================================================
Gender
============================================================
0


============================================================
Location
============================================================
0


============================================================
Tenure_Months
============================================================
0

In [20]:
for name, df in customer_df.items():

    print('=' * 60)

    print(name)

    print('=' * 60)

    missing_pct = (
        df.isnull().sum()
        / len(df)
    ) * 100

    print(
        missing_pct.round(2)
    )

    print('\n')

============================================================
CustomerID
============================================================
0.0


============================================================
Gender
============================================================
0.0


============================================================
Location
============================================================
0.0


============================================================
Tenure_Months
============================================================
0.0

In [21]:
sales_df.describe()

,Transaction_Date,Quantity,Avg_Price,Delivery_Charges
count,52924,52924.000000,52924.000000,52924.000000
mean,2019-07-05 19:16:09.450532864,4.497638,52.237646,10.517630
min,2019-01-01 00:00:00,1.000000,0.390000,0.000000
25%,2019-04-12 00:00:00,1.000000,5.700000,6.000000
50%,2019-07-13 00:00:00,1.000000,16.990000,6.000000
75%,2019-09-27 00:00:00,2.000000,102.130000,6.500000
max,2019-12-31 00:00:00,900.000000,355.740000,521.360000
std,NaN,20.104711,64.006882,19.475613

In [22]:
sales_df['Month'] = sales_df['Transaction_Date'].dt.month_name()

In [23]:
sales_df.describe()

,Transaction_Date,Quantity,Avg_Price,Delivery_Charges
count,52924,52924.000000,52924.000000,52924.000000
mean,2019-07-05 19:16:09.450532864,4.497638,52.237646,10.517630
min,2019-01-01 00:00:00,1.000000,0.390000,0.000000
25%,2019-04-12 00:00:00,1.000000,5.700000,6.000000
50%,2019-07-13 00:00:00,1.000000,16.990000,6.000000
75%,2019-09-27 00:00:00,2.000000,102.130000,6.500000
max,2019-12-31 00:00:00,900.000000,355.740000,521.360000
std,NaN,20.104711,64.006882,19.475613

In [24]:
marketing_df['Month'] = marketing_df['Date'].dt.month_name()

In [25]:
marketing_df.describe()

                      Date  Offline_Spend  Online_Spend
count                  365     365.000000    365.000000
mean   2019-07-02 00:00:00    2843.561644   1905.880740
min    2019-01-01 00:00:00     500.000000    320.250000
25%    2019-04-02 00:00:00    2500.000000   1258.600000
50%    2019-07-02 00:00:00    3000.000000   1881.940000
75%    2019-10-01 00:00:00    3500.000000   2435.120000
max    2019-12-31 00:00:00    5000.000000   4556.930000
std                    NaN     952.292448    808.856853

In [30]:
merged_df = sales_df.merge(
    customer_df,
    on='CustomerID',
    how='left'
)

In [35]:
print(merged_df.shape)

merged_df.head()

(52924, 15)

,CustomerID,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status,Month,Gender,Location,Tenure_Months,GST
0,17850,16679,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used,January,M,Chicago,12,0.10
1,17850,16680,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used,January,M,Chicago,12,0.10
2,17850,16681,2019-01-01,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,1,2.05,6.5,Used,January,M,Chicago,12,0.10
3,17850,16682,2019-01-01,GGOEGAAB010516,Google Men's 100% Cotton Short Sleeve Hero Tee...,Apparel,5,17.53,6.5,Not Used,January,M,Chicago,12,0.18
4,17850,16682,2019-01-01,GGOEGBJL013999,Google Canvas Tote Natural/Navy,Bags,1,16.50,6.5,Used,January,M,Chicago,12,0.18

In [32]:
merged_df = merged_df.merge(
    tax_df,
    on='Product_Category',
    how='left'
)

In [34]:
print(merged_df.shape)

merged_df.head()

(52924, 15)

,CustomerID,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status,Month,Gender,Location,Tenure_Months,GST
0,17850,16679,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used,January,M,Chicago,12,0.10
1,17850,16680,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used,January,M,Chicago,12,0.10
2,17850,16681,2019-01-01,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,1,2.05,6.5,Used,January,M,Chicago,12,0.10
3,17850,16682,2019-01-01,GGOEGAAB010516,Google Men's 100% Cotton Short Sleeve Hero Tee...,Apparel,5,17.53,6.5,Not Used,January,M,Chicago,12,0.18
4,17850,16682,2019-01-01,GGOEGBJL013999,Google Canvas Tote Natural/Navy,Bags,1,16.50,6.5,Used,January,M,Chicago,12,0.18

In [36]:
merged_df = merged_df.merge(
    disc_coupon_df,
    on=['Month', 'Product_Category'],
    how='left'
)

In [37]:
print(merged_df.shape)

merged_df.head()

(52924, 17)

,CustomerID,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status,Month,Gender,Location,Tenure_Months,GST,Coupon_Code,Discount_pct
0,17850,16679,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used,January,M,Chicago,12,0.10,NaN,NaN
1,17850,16680,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used,January,M,Chicago,12,0.10,NaN,NaN
2,17850,16681,2019-01-01,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,1,2.05,6.5,Used,January,M,Chicago,12,0.10,NaN,NaN
3,17850,16682,2019-01-01,GGOEGAAB010516,Google Men's 100% Cotton Short Sleeve Hero Tee...,Apparel,5,17.53,6.5,Not Used,January,M,Chicago,12,0.18,NaN,NaN
4,17850,16682,2019-01-01,GGOEGBJL013999,Google Canvas Tote Natural/Navy,Bags,1,16.50,6.5,Used,January,M,Chicago,12,0.18,NaN,NaN

In [38]:
merged_df = merged_df.merge(
    marketing_df,
    left_on='Transaction_Date',
    right_on='Date',
    how='left'
)

In [39]:
print(merged_df.shape)

merged_df.head()

(52924, 21)

,CustomerID,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status,...,Gender,Location,Tenure_Months,GST,Coupon_Code,Discount_pct,Date,Offline_Spend,Online_Spend,Month_y
0,17850,16679,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used,...,M,Chicago,12,0.10,NaN,NaN,2019-01-01,4500,2424.5,January
1,17850,16680,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used,...,M,Chicago,12,0.10,NaN,NaN,2019-01-01,4500,2424.5,January
2,17850,16681,2019-01-01,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,1,2.05,6.5,Used,...,M,Chicago,12,0.10,NaN,NaN,2019-01-01,4500,2424.5,January
3,17850,16682,2019-01-01,GGOEGAAB010516,Google Men's 100% Cotton Short Sleeve Hero Tee...,Apparel,5,17.53,6.5,Not Used,...,M,Chicago,12,0.18,NaN,NaN,2019-01-01,4500,2424.5,January
4,17850,16682,2019-01-01,GGOEGBJL013999,Google Canvas Tote Natural/Navy,Bags,1,16.50,6.5,Used,...,M,Chicago,12,0.18,NaN,NaN,2019-01-01,4500,2424.5,January

In [40]:
merged_df.drop(
    columns='Date',
    inplace=True
)

In [41]:
print(merged_df.shape)

merged_df.head()

(52924, 20)

,CustomerID,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status,Month_x,Gender,Location,Tenure_Months,GST,Coupon_Code,Discount_pct,Offline_Spend,Online_Spend,Month_y
0,17850,16679,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used,January,M,Chicago,12,0.10,NaN,NaN,4500,2424.5,January
1,17850,16680,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used,January,M,Chicago,12,0.10,NaN,NaN,4500,2424.5,January
2,17850,16681,2019-01-01,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,1,2.05,6.5,Used,January,M,Chicago,12,0.10,NaN,NaN,4500,2424.5,January
3,17850,16682,2019-01-01,GGOEGAAB010516,Google Men's 100% Cotton Short Sleeve Hero Tee...,Apparel,5,17.53,6.5,Not Used,January,M,Chicago,12,0.18,NaN,NaN,4500,2424.5,January
4,17850,16682,2019-01-01,GGOEGBJL013999,Google Canvas Tote Natural/Navy,Bags,1,16.50,6.5,Used,January,M,Chicago,12,0.18,NaN,NaN,4500,2424.5,January

In [42]:
merged_df.columns

Index(['CustomerID', 'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'Month_x', 'Gender', 'Location',
       'Tenure_Months', 'GST', 'Coupon_Code', 'Discount_pct', 'Offline_Spend',
       'Online_Spend', 'Month_y'],
      dtype='object')

In [43]:
merged_df.isnull().sum()

CustomerID                 0
Transaction_ID             0
Transaction_Date           0
Product_SKU                0
Product_Description        0
Product_Category           0
Quantity                   0
Avg_Price                  0
Delivery_Charges           0
Coupon_Status              0
Month_x                    0
Gender                     0
Location                   0
Tenure_Months              0
GST                        0
Coupon_Code            48408
Discount_pct           48408
Offline_Spend              0
Online_Spend               0
Month_y                    0
dtype: int64

In [44]:
(
    merged_df.isnull().sum()
    / len(merged_df)
) * 100

CustomerID              0.000000
Transaction_ID          0.000000
Transaction_Date        0.000000
Product_SKU             0.000000
Product_Description     0.000000
Product_Category        0.000000
Quantity                0.000000
Avg_Price               0.000000
Delivery_Charges        0.000000
Coupon_Status           0.000000
Month_x                 0.000000
Gender                  0.000000
Location                0.000000
Tenure_Months           0.000000
GST                     0.000000
Coupon_Code            91.467009
Discount_pct           91.467009
Offline_Spend           0.000000
Online_Spend            0.000000
Month_y                 0.000000
dtype: float64

In [45]:
merged_df['GST'] = (
    merged_df['GST']
    .fillna(0)
)

merged_df['Discount_pct'] = (
    merged_df['Discount_pct']
    .fillna(0)
)

In [46]:
merged_df['Offline_Spend'] = (
    merged_df['Offline_Spend']
    .fillna(0)
)

merged_df['Online_Spend'] = (
    merged_df['Online_Spend']
    .fillna(0)
)

In [47]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52924 entries, 0 to 52923
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CustomerID           52924 non-null  object
 1   Transaction_ID       52924 non-null  object
 2   Transaction_Date     52924 non-null  datetime64[ns]
 3   Product_SKU          52924 non-null  object
 4   Product_Description  52924 non-null  object
 5   Product_Category     52924 non-null  object
 6   Quantity             52924 non-null  int64
 7   Avg_Price            52924 non-null  float64
 8   Delivery_Charges     52924 non-null  float64
 9   Coupon_Status        52924 non-null  object
 10  Month_x              52924 non-null  object
 11  Gender               52924 non-null  object
 12  Location             52924 non-null  object
 13  Tenure_Months        52924 non-null  int64
 14  GST                  52924 non-null  float64
 15  Coupon_Code          4516 non-null   object
 16  Discount_pct         52924 non-null  float64
 17  Offline_Spend        52924 non-null  int64
 18  Online_Spend         52924 non-null  float64
 19  Month_y              52924 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(3), object(11)
memory usage: 8.1+ MB

In [48]:
required_columns = [
    'Quantity',
    'Avg_Price',
    'Discount_pct',
    'GST',
    'Delivery_Charges'
]

print(merged_df[required_columns].head())

   Quantity  Avg_Price  Discount_pct   GST  Delivery_Charges
0         1     153.71           0.0  0.10               6.5
1         1     153.71           0.0  0.10               6.5
2         1       2.05           0.0  0.10               6.5
3         5      17.53           0.0  0.18               6.5
4         1      16.50           0.0  0.18               6.5

In [49]:
numeric_cols = [
    'Quantity',
    'Avg_Price',
    'Discount_pct',
    'GST',
    'Delivery_Charges'
]

for col in numeric_cols:

    merged_df[col] = pd.to_numeric(
        merged_df[col],
        errors='coerce'
    )

In [50]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52924 entries, 0 to 52923
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CustomerID           52924 non-null  object
 1   Transaction_ID       52924 non-null  object
 2   Transaction_Date     52924 non-null  datetime64[ns]
 3   Product_SKU          52924 non-null  object
 4   Product_Description  52924 non-null  object
 5   Product_Category     52924 non-null  object
 6   Quantity             52924 non-null  int64
 7   Avg_Price            52924 non-null  float64
 8   Delivery_Charges     52924 non-null  float64
 9   Coupon_Status        52924 non-null  object
 10  Month_x              52924 non-null  object
 11  Gender               52924 non-null  object
 12  Location             52924 non-null  object
 13  Tenure_Months        52924 non-null  int64
 14  GST                  52924 non-null  float64
 15  Coupon_Code          4516 non-null   object
 16  Discount_pct         52924 non-null  float64
 17  Offline_Spend        52924 non-null  int64
 18  Online_Spend         52924 non-null  float64
 19  Month_y              52924 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(3), object(11)
memory usage: 8.1+ MB

In [51]:
merged_df[numeric_cols] = (
    merged_df[numeric_cols]
    .fillna(0)
)

In [52]:
merged_df[numeric_cols]

       Quantity  Avg_Price  Discount_pct   GST  Delivery_Charges
0             1     153.71           0.0  0.10              6.50
1             1     153.71           0.0  0.10              6.50
2             1       2.05           0.0  0.10              6.50
3             5      17.53           0.0  0.18              6.50
4             1      16.50           0.0  0.18              6.50
...         ...        ...           ...   ...               ...
52919         1     121.30           0.0  0.10              6.50
52920         1      48.92           0.0  0.18              6.50
52921         1     151.88           0.0  0.10              6.50
52922         5      80.52           0.0  0.10              6.50
52923         4      80.52           0.0  0.10             19.99

[52924 rows x 5 columns]

In [53]:
if merged_df['Discount_pct'].max() > 1:

    merged_df['Discount_pct'] = (
        merged_df['Discount_pct'] / 100
    )

In [54]:
 merged_df['Discount_pct']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
52919    0.0
52920    0.0
52921    0.0
52922    0.0
52923    0.0
Name: Discount_pct, Length: 52924, dtype: float64

In [55]:
if merged_df['GST'].max() > 1:

    merged_df['GST'] = (
        merged_df['GST'] / 100
    )

In [56]:
print(
    merged_df[
        ['Discount_pct','GST']
    ].head()
)

   Discount_pct   GST
0           0.0  0.10
1           0.0  0.10
2           0.0  0.10
3           0.0  0.18
4           0.0  0.18

In [57]:
merged_df['Base_Amount'] = (
    merged_df['Quantity']
    * merged_df['Avg_Price']
)

In [59]:
merged_df

,CustomerID,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status,...,Gender,Location,Tenure_Months,GST,Coupon_Code,Discount_pct,Offline_Spend,Online_Spend,Month_y,Base_Amount
0,17850,16679,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.50,Used,...,M,Chicago,12,0.10,NaN,0.0,4500,2424.50,January,153.71
1,17850,16680,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.50,Used,...,M,Chicago,12,0.10,NaN,0.0,4500,2424.50,January,153.71
2,17850,16681,2019-01-01,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,1,2.05,6.50,Used,...,M,Chicago,12,0.10,NaN,0.0,4500,2424.50,January,2.05
3,17850,16682,2019-01-01,GGOEGAAB010516,Google Men's 100% Cotton Short Sleeve Hero Tee...,Apparel,5,17.53,6.50,Not Used,...,M,Chicago,12,0.18,NaN,0.0,4500,2424.50,January,87.65
4,17850,16682,2019-01-01,GGOEGBJL013999,Google Canvas Tote Natural/Navy,Bags,1,16.50,6.50,Used,...,M,Chicago,12,0.18,NaN,0.0,4500,2424.50,January,16.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52919,14410,48493,2019-12-31,GGOENEBB078899,Nest Cam Indoor Security Camera - USA,Nest-USA,1,121.30,6.50,Clicked,...,F,New York,45,0.10,NaN,0.0,4000,2058.75,December,121.30
52920,14410,48494,2019-12-31,GGOEGAEB091117,Google Zip Hoodie Black,Apparel,1,48.92,6.50,Used,...,F,New York,45,0.18,NaN,0.0,4000,2058.75,December,48.92
52921,14410,48495,2019-12-31,GGOENEBQ084699,Nest Learning Thermostat 3rd Gen-USA - White,Nest-USA,1,151.88,6.50,Used,...,F,New York,45,0.10,NaN,0.0,4000,2058.75,December,151.88
52922,14600,48496,2019-12-31,GGOENEBQ079199,Nest Protect Smoke + CO White Wired Alarm-USA,Nest-USA,5,80.52,6.50,Clicked,...,F,California,7,0.10,NaN,0.0,4000,2058.75,December,402.60
52923,14600,48497,2019-12-31,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,4,80.52,19.99,Clicked,...,F,California,7,0.10,NaN,0.0,4000,2058.75,December,322.08

In [60]:
merged_df['Discounted_Amount'] = (
    merged_df['Base_Amount']
    * (1 - merged_df['Discount_pct'])
)

In [61]:
merged_df

,CustomerID,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status,...,Location,Tenure_Months,GST,Coupon_Code,Discount_pct,Offline_Spend,Online_Spend,Month_y,Base_Amount,Discounted_Amount
0,17850,16679,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.50,Used,...,Chicago,12,0.10,NaN,0.0,4500,2424.50,January,153.71,153.71
1,17850,16680,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.50,Used,...,Chicago,12,0.10,NaN,0.0,4500,2424.50,January,153.71,153.71
2,17850,16681,2019-01-01,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,1,2.05,6.50,Used,...,Chicago,12,0.10,NaN,0.0,4500,2424.50,January,2.05,2.05
3,17850,16682,2019-01-01,GGOEGAAB010516,Google Men's 100% Cotton Short Sleeve Hero Tee...,Apparel,5,17.53,6.50,Not Used,...,Chicago,12,0.18,NaN,0.0,4500,2424.50,January,87.65,87.65
4,17850,16682,2019-01-01,GGOEGBJL013999,Google Canvas Tote Natural/Navy,Bags,1,16.50,6.50,Used,...,Chicago,12,0.18,NaN,0.0,4500,2424.50,January,16.50,16.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52919,14410,48493,2019-12-31,GGOENEBB078899,Nest Cam Indoor Security Camera - USA,Nest-USA,1,121.30,6.50,Clicked,...,New York,45,0.10,NaN,0.0,4000,2058.75,December,121.30,121.30
52920,14410,48494,2019-12-31,GGOEGAEB091117,Google Zip Hoodie Black,Apparel,1,48.92,6.50,Used,...,New York,45,0.18,NaN,0.0,4000,2058.75,December,48.92,48.92
52921,14410,48495,2019-12-31,GGOENEBQ084699,Nest Learning Thermostat 3rd Gen-USA - White,Nest-USA,1,151.88,6.50,Used,...,New York,45,0.10,NaN,0.0,4000,2058.75,December,151.88,151.88
52922,14600,48496,2019-12-31,GGOENEBQ079199,Nest Protect Smoke + CO White Wired Alarm-USA,Nest-USA,5,80.52,6.50,Clicked,...,California,7,0.10,NaN,0.0,4000,2058.75,December,402.60,402.60
52923,14600,48497,2019-12-31,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,4,80.52,19.99,Clicked,...,California,7,0.10,NaN,0.0,4000,2058.75,December,322.08,322.08

In [62]:
merged_df['Taxed_Amount'] = (
    merged_df['Discounted_Amount']
    * (1 + merged_df['GST'])
)

In [63]:
merged_df

,CustomerID,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status,...,Tenure_Months,GST,Coupon_Code,Discount_pct,Offline_Spend,Online_Spend,Month_y,Base_Amount,Discounted_Amount,Taxed_Amount
0,17850,16679,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.50,Used,...,12,0.10,NaN,0.0,4500,2424.50,January,153.71,153.71,169.0810
1,17850,16680,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.50,Used,...,12,0.10,NaN,0.0,4500,2424.50,January,153.71,153.71,169.0810
2,17850,16681,2019-01-01,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,1,2.05,6.50,Used,...,12,0.10,NaN,0.0,4500,2424.50,January,2.05,2.05,2.2550
3,17850,16682,2019-01-01,GGOEGAAB010516,Google Men's 100% Cotton Short Sleeve Hero Tee...,Apparel,5,17.53,6.50,Not Used,...,12,0.18,NaN,0.0,4500,2424.50,January,87.65,87.65,103.4270
4,17850,16682,2019-01-01,GGOEGBJL013999,Google Canvas Tote Natural/Navy,Bags,1,16.50,6.50,Used,...,12,0.18,NaN,0.0,4500,2424.50,January,16.50,16.50,19.4700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52919,14410,48493,2019-12-31,GGOENEBB078899,Nest Cam Indoor Security Camera - USA,Nest-USA,1,121.30,6.50,Clicked,...,45,0.10,NaN,0.0,4000,2058.75,December,121.30,121.30,133.4300
52920,14410,48494,2019-12-31,GGOEGAEB091117,Google Zip Hoodie Black,Apparel,1,48.92,6.50,Used,...,45,0.18,NaN,0.0,4000,2058.75,December,48.92,48.92,57.7256
52921,14410,48495,2019-12-31,GGOENEBQ084699,Nest Learning Thermostat 3rd Gen-USA - White,Nest-USA,1,151.88,6.50,Used,...,45,0.10,NaN,0.0,4000,2058.75,December,151.88,151.88,167.0680
52922,14600,48496,2019-12-31,GGOENEBQ079199,Nest Protect Smoke + CO White Wired Alarm-USA,Nest-USA,5,80.52,6.50,Clicked,...,7,0.10,NaN,0.0,4000,2058.75,December,402.60,402.60,442.8600
52923,14600,48497,2019-12-31,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,4,80.52,19.99,Clicked,...,7,0.10,NaN,0.0,4000,2058.75,December,322.08,322.08,354.2880

In [64]:
merged_df['Invoice_Value'] = (

    merged_df['Taxed_Amount']

    + merged_df['Delivery_Charges']

)

In [65]:
merged_df

,CustomerID,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status,...,GST,Coupon_Code,Discount_pct,Offline_Spend,Online_Spend,Month_y,Base_Amount,Discounted_Amount,Taxed_Amount,Invoice_Value
0,17850,16679,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.50,Used,...,0.10,NaN,0.0,4500,2424.50,January,153.71,153.71,169.0810,175.5810
1,17850,16680,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.50,Used,...,0.10,NaN,0.0,4500,2424.50,January,153.71,153.71,169.0810,175.5810
2,17850,16681,2019-01-01,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,1,2.05,6.50,Used,...,0.10,NaN,0.0,4500,2424.50,January,2.05,2.05,2.2550,8.7550
3,17850,16682,2019-01-01,GGOEGAAB010516,Google Men's 100% Cotton Short Sleeve Hero Tee...,Apparel,5,17.53,6.50,Not Used,...,0.18,NaN,0.0,4500,2424.50,January,87.65,87.65,103.4270,109.9270
4,17850,16682,2019-01-01,GGOEGBJL013999,Google Canvas Tote Natural/Navy,Bags,1,16.50,6.50,Used,...,0.18,NaN,0.0,4500,2424.50,January,16.50,16.50,19.4700,25.9700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52919,14410,48493,2019-12-31,GGOENEBB078899,Nest Cam Indoor Security Camera - USA,Nest-USA,1,121.30,6.50,Clicked,...,0.10,NaN,0.0,4000,2058.75,December,121.30,121.30,133.4300,139.9300
52920,14410,48494,2019-12-31,GGOEGAEB091117,Google Zip Hoodie Black,Apparel,1,48.92,6.50,Used,...,0.18,NaN,0.0,4000,2058.75,December,48.92,48.92,57.7256,64.2256
52921,14410,48495,2019-12-31,GGOENEBQ084699,Nest Learning Thermostat 3rd Gen-USA - White,Nest-USA,1,151.88,6.50,Used,...,0.10,NaN,0.0,4000,2058.75,December,151.88,151.88,167.0680,173.5680
52922,14600,48496,2019-12-31,GGOENEBQ079199,Nest Protect Smoke + CO White Wired Alarm-USA,Nest-USA,5,80.52,6.50,Clicked,...,0.10,NaN,0.0,4000,2058.75,December,402.60,402.60,442.8600,449.3600
52923,14600,48497,2019-12-31,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,4,80.52,19.99,Clicked,...,0.10,NaN,0.0,4000,2058.75,December,322.08,322.08,354.2880,374.2780

In [66]:
merged_df[[
    'Quantity',
    'Avg_Price',
    'Discount_pct',
    'GST',
    'Delivery_Charges',
    'Invoice_Value'
]].head()

   Quantity  Avg_Price  Discount_pct   GST  Delivery_Charges  Invoice_Value
0         1     153.71           0.0  0.10               6.5        175.581
1         1     153.71           0.0  0.10               6.5        175.581
2         1       2.05           0.0  0.10               6.5          8.755
3         5      17.53           0.0  0.18               6.5        109.927
4         1      16.50           0.0  0.18               6.5         25.970

In [67]:
total_revenue = (
    merged_df['Invoice_Value']
    .sum()
)

print(
    f'Total Revenue: ₹{total_revenue:,.2f}'
)

Total Revenue: ₹5,673,745.82

In [68]:
total_orders = (
    merged_df['Transaction_ID']
    .nunique()
)

print(
    f'Total Orders: {total_orders}'
)

Total Orders: 25061

In [69]:
total_customers = (
    merged_df['CustomerID']
    .nunique()
)

print(
    f'Total Customers: {total_customers}'
)

Total Customers: 1468

In [70]:
aov = (
    total_revenue
    / total_orders
)

print(
    f'Average Order Value: ₹{aov:,.2f}'
)

Average Order Value: ₹226.40

In [71]:
merged_df[['Invoice_Value']].describe()

       Invoice_Value
count   52924.000000
mean      107.205537
std       181.734258
min         4.861600
25%        21.094560
50%        47.288200
75%       141.547000
max     11044.009500